openapi: 3.0.3
info:
  title: RecipeBook API
  version: 0.6.0
  description: >
    # About

    Something about this API...

servers:
  - url: http://127.0.0.1:8080/api/v1/
    description: local deployment of web-api

components:
  schemas:
    # nutrient
    Nutrient:
      type: object
      properties:
        id:
          type: integer
          example: 6
        name:
          type: string
          example: dietary_fiber
        daily_value:
          type: number
          example: 28.0
        unit:
          type: string
          example: g
        nutrient_group:
          type: string
          example: carbohydrates
        parent_name:
          type: string
          example: carbohydrate
    # product
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 3
        product_type:
          type: string
          example: food
        name:
          type: string
          example: Tomato
        brand:
          type: string
        subtitle:
          type: string
        description:
          type: string
        density:
          type: number
          example: 1.0
        serving_size:
          type: number
          example: 100.0
        is_private:
          type: boolean
          example: false
        created_at:
          type: string
          example: "2022-06-27T01:41:41.850918Z"
        updated_at:
          type: string
          example: "2022-06-27T01:41:41.850934Z"
    ProductShort:
      type: object
      properties:
        id:
          type: integer
          example: 321360
        product_type:
          type: string
          example: food
        name:
          type: string
          example: Tomatoes, grape, raw
        brand:
          type: string
          example: ""
        subtitle:
          type: string
          example: ""
        is_private:
          type: boolean
          example: false
        created_at:
          type: string
          example: "2022-11-04T13:29:03.400873Z"
        updated_at:
          type: string
          example: "2022-11-04T13:29:03.400873Z"
    DeleteProductPayload:
      type: object
      properties:
        id:
          type: integer
          example: 1
    # custom_unit
    CustomUnit:
      type: object
      properties:
        name:
          type: string
          example: medium
        amount:
          type: number
          example: 123.0
        unit:
          type: string
          example: g
        product_id:
          type: integer
          example: 3
    CreateCustomUnitPayload:
      type: object
      properties:
        name:
          type: string
          example: medium
        amount:
          type: number
          example: 123.0
        unit:
          type: string
          example: g
    # food
    Food:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: Tomato
        brand:
          type: string
        subtitle:
          type: string
        description:
          type: string
        density:
          type: number
          example: 1.0
        serving_size:
          type: number
          example: 100.0
        nutrients:
          type: object
          additionalProperties:
            type: number
          example:
            protein: 0.9
            dietary_fiber: 1.2
            energy: 18.0
            carbohydrate: 3.9
            sugars: 2.6
            fat: 0.2
        custom_units:
          type: array
          items:
            $ref: "#/components/schemas/CustomUnit"
        is_private:
          type: boolean
          example: false
        created_at:
          type: string
          example: "2022-06-27T01:41:41.850918Z"
        updated_at:
          type: string
          example: "2022-06-27T01:41:41.850934Z"
    CreateFoodPayload:
      type: object
      properties:
        name:
          type: string
          example: Tomato
        brand:
          type: string
        subtitle:
          type: string
        description:
          type: string
        density:
          type: number
          example: 1.0
        serving_size:
          type: number
          example: 100.0
        nutrients:
          type: object
          additionalProperties:
            type: number
          example:
            protein: 0.9
            dietary_fiber: 1.2
            energy: 18.0
            carbohydrate: 3.9
            sugars: 2.6
            fat: 0.2
        custom_units:
          type: array
          items:
            $ref: "#/components/schemas/CreateCustomUnitPayload"
        is_private:
          type: boolean
          example: false
    UpdateFoodPayload:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: Tomato
        brand:
          type: string
        subtitle:
          type: string
        description:
          type: string
        density:
          type: number
          example: 1.0
        serving_size:
          type: number
          example: 100.0
        nutrients:
          type: object
          additionalProperties:
            type: number
          example:
            protein: 0.9
            dietary_fiber: 1.2
            energy: 18.0
            carbohydrate: 3.9
            sugars: 2.6
            fat: 0.2
        custom_units:
          type: array
          items:
            $ref: "#/components/schemas/CustomUnit"
        is_private:
          type: boolean
          example: false
    # ingredient
    IngredientProductDetailsWithNutrients:
      type: object
      properties:
        ingredient_id:
          type: integer
          example: 6
        product_id:
          type: integer
          example: 4
        amount:
          type: number
          example: 125.0
        unit:
          type: string
          example: g
        product_type:
          type: string
          example: food
        name:
          type: string
          example: Ground Beef
        density:
          type: number
          example: 1.0
        nutrients:
          type: object
          additionalProperties:
            type: number
          example:
            protein: 14.0
            energy: 332.0
            sugars: 0
            carbohydrate: 0
            fat: 30.0
    IngredientDetails:
      type: object
      properties:
        id:
          type: integer
          example: 6
        product_id:
          type: integer
          example: 4
        products:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/IngredientProductDetailsWithNutrients"
    IngredientProductPayload:
      type: object
      properties:
        product_id:
          type: integer
          example: 4
        amount:
          type: number
          example: 125.0
        unit:
          type: string
          example: g
    CreateIngredientPayload:
      type: object
      properties:
        id:
          type: integer
          description: should store a temporary id
          example: -6
        product_id:
          type: integer
          example: 4
        products:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/IngredientProductPayload"
    UpdateIngredientPayload:
      type: object
      properties:
        id:
          type: integer
          example: 6
        product_id:
          type: integer
          example: 4
        products:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/IngredientProductPayload"
    # direction
    DirectionPartDetails:
      type: object
      properties:
        step_number:
          type: integer
          example: 1
        direction_part_type:
          type: string
          enum:
            - ingredient
            - note
            - warning
            - tip
          example: tip
        comment_text:
          type: string
          example: You can flip it after 8 min, but not necessary
        ingredient_id:
          type: integer
        ingredient_amount:
          type: number
    DirectionDetails:
      type: object
      properties:
        id:
          type: integer
          example: 4
        step_number:
          type: integer
          example: 1
        name:
          type: string
          example: Bake the patty
        temperature_value:
          type: number
          example: 82.22222
        temperature_unit:
          type: string
          example: F
        duration_value:
          type: integer
          example: 900
        duration_unit:
          type: string
          example: min
        steps:
          type: array
          items:
            $ref: "#/components/schemas/DirectionPartDetails"
    DirectionPartPayload:
      type: object
      properties:
        step_number:
          type: integer
          example: 1
        direction_part_type:
          type: string
          enum:
            - ingredient
            - note
            - warning
            - tip
          example: tip
        comment_text:
          type: string
          example: You can flip it after 8 min, but not necessary
        ingredient_id:
          type: integer
        ingredient_amount:
          type: number
    CreateDirectionPayload:
      type: object
      properties:
        step_number:
          type: integer
          example: 1
        name:
          type: string
          example: Bake the patty
        temperature_value:
          type: number
          example: 82.22222
        temperature_unit:
          type: string
          example: F
        duration_value:
          type: integer
          example: 900
        duration_unit:
          type: string
          example: min
        steps:
          type: array
          items:
            $ref: "#/components/schemas/DirectionPartPayload"
    UpdateDirectionPayload:
      type: object
      properties:
        id:
          type: integer
          example: 6
        step_number:
          type: integer
          example: 1
        name:
          type: string
          example: Bake the patty
        temperature_value:
          type: number
          example: 82.22222
        temperature_unit:
          type: string
          example: F
        duration_value:
          type: integer
          example: 900
        duration_unit:
          type: string
          example: min
        steps:
          type: array
          items:
            $ref: "#/components/schemas/DirectionPartPayload"
    # recipe
    Recipe:
      type: object
      properties:
        id:
          type: integer
          example: 6
        name:
          type: string
          example: Hamburger
        brand:
          type: string
          example: Homemade
        subtitle:
          type: string
        description:
          type: string
        density:
          type: number
          example: 1.0
        serving_size:
          type: number
          example: 479.7476
        custom_units:
          type: array
          items:
            $ref: "#/components/schemas/CustomUnit"
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/IngredientDetails"
        directions:
          type: array
          items:
            $ref: "#/components/schemas/DirectionDetails"
        is_private:
          type: boolean
          example: false
        created_at:
          type: string
          example: "2022-06-27T01:41:41.850918Z"
        updated_at:
          type: string
          example: "2022-06-27T01:41:41.850934Z"
    CreateRecipePayload:
      type: object
      properties:
        name:
          type: string
          example: Hamburger
        brand:
          type: string
          example: Homemade
        subtitle:
          type: string
        description:
          type: string
        density:
          type: number
          example: 1.0
        serving_size:
          type: number
          example: 479.7476
        custom_units:
          type: array
          items:
            $ref: "#/components/schemas/CreateCustomUnitPayload"
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/CreateIngredientPayload"
        directions:
          type: array
          items:
            $ref: "#/components/schemas/CreateDirectionPayload"
        is_private:
          type: boolean
          example: false
    UpdateRecipePayload:
      type: object
      properties:
        id:
          type: integer
          example: 6
        name:
          type: string
          example: Hamburger
        brand:
          type: string
          example: Homemade
        subtitle:
          type: string
        description:
          type: string
        density:
          type: number
          example: 1.0
        serving_size:
          type: number
          example: 479.7476
        custom_units:
          type: array
          items:
            $ref: "#/components/schemas/CustomUnit"
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/UpdateIngredientPayload"
        directions:
          type: array
          items:
            $ref: "#/components/schemas/UpdateDirectionPayload"
        is_private:
          type: boolean
          example: false
    # journal
    JournalGroup:
      type: object
      properties:
        order_number:
          type: integer
          example: 2
        name:
          type: string
          example: lunch
        user_id:
          type: integer
          example: 1
    JournalEntry:
      type: object
      properties:
        id:
          type: integer
          example: 2
        user_id:
          type: integer
          example: 1
        entry_date:
          type: string
          example: "2022-11-04"
        entry_time:
          type: string
          example: "13:29:03"
        product_id:
          type: integer
          example: 6
        amount:
          type: number
          example: 450.5
        unit:
          type: string
          example: g
        journal_group_num:
          type: integer
          example: 2
    CreateJournalEntryPayload:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        entry_date:
          type: string
          example: "2022-11-04"
        entry_time:
          type: string
          example: "13:29:03"
        product_id:
          type: integer
          example: 6
        amount:
          type: number
          example: 450.5
        unit:
          type: string
          example: g
        journal_group_num:
          type: integer
          example: 2
    DeleteJournalEntryPayload:
      type: object
      properties:
        id:
          type: integer
          example: 2
    JournalEntryDetailed:
      type: object
      properties:
        id:
          type: integer
          example: 2
        user_id:
          type: integer
          example: 1
        entry_date:
          type: string
          example: "2022-11-04"
        entry_time:
          type: string
          example: "13:29:03"
        product_id:
          type: integer
          example: 6
        product:
          type: object
          $ref: "#/components/schemas/Product"
        amount:
          type: number
          example: 450.5
        unit:
          type: string
          example: g
        journal_group_num:
          type: integer
          example: 2
        nutrients:
          type: object
          additionalProperties:
            type: number
          example:
            protein: 0.9
            dietary_fiber: 1.2
            energy: 18.0
            carbohydrate: 3.9
            sugars: 2.6
            fat: 0.2
        custom_units:
          type: array
          items:
            $ref: "#/components/schemas/CustomUnit"
tags:
  - name: meta
    description: All `meta` related endpoints
  - name: product
    description: All `product` related endpoints
  - name: food
    description: All `food` related endpoints
  - name: recipe
    description: All `recipe` related endpoints
  - name: journal
    description: All `journal` related endpoints

x-tagGroups:
  - name: General
    tags:
      - meta
      - product
      - food
      - recipe
      - journal

paths:
  /meta/nutrients:
    get:
      tags:
        - meta
      summary: Get all nutrients
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Nutrient"

  /product:
    get:
      tags:
        - product
      summary: Find products

      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 100
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            example: 0
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            example: 0
        - name: product_type
          in: query
          required: false
          schema:
            type: string
            enum:
              - food
              - recipe
        - name: filter
          in: query
          required: false
          schema:
            type: string
            example: Tomato

      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductShort"
        "404":
          description: Not Found

  /product/created:
    get:
      tags:
        - product
      summary: Find products created by user

      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 100
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            example: 0
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            example: 0
        - name: product_type
          in: query
          required: false
          schema:
            type: string
            enum:
              - food
              - recipe
        - name: filter
          in: query
          required: false
          schema:
            type: string
            example: Tomato

      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductShort"
        "404":
          description: Not Found

  /product/favorite:
    get:
      tags:
        - product
      summary: Find favorite products

      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 100
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            example: 0
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            example: 0
        - name: product_type
          in: query
          required: false
          schema:
            type: string
            enum:
              - food
              - recipe
        - name: filter
          in: query
          required: false
          schema:
            type: string
            example: Tomato

      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductShort"
        "404":
          description: Not Found

  /product/delete:
    post:
      tags:
        - product
      summary: Delete a product by id
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/DeleteProductPayload"
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found

  /food/{id}:
    get:
      tags:
        - food
      summary: Find a food by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 3
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Food"
        "404":
          description: Not Found

  /food/create:
    post:
      tags:
        - food
      summary: Create a food
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/CreateFoodPayload"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Food"
        "404":
          description: Not Found

  /food/update:
    post:
      tags:
        - food
      summary: Update a food
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/UpdateFoodPayload"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Food"
        "404":
          description: Not Found

  /recipe/{id}:
    get:
      tags:
        - recipe
      summary: Find a recipe by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 6
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Recipe"
        "404":
          description: Not Found

  /recipe/create:
    post:
      tags:
        - recipe
      summary: Create a recipe
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/CreateRecipePayload"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Recipe"
        "404":
          description: Not Found

  /recipe/update:
    post:
      tags:
        - recipe
      summary: Update a recipe
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/UpdateRecipePayload"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Recipe"
        "404":
          description: Not Found

  /journal/groups:
    get:
      tags:
        - journal
      summary: Get all journal groups
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/JournalGroup"
              example:
                - order_number: 1
                  name: breakfast
                  user_id: 1
                - order_number: 2
                  name: lunch
                  user_id: 1
                - order_number: 3
                  name: dinner
                  user_id: 1
        "404":
          description: Not Found

  /journal/groups/update:
    post:
      tags:
        - journal
      summary: Update all journal groups
      description: This request will replace all existing journal groups for a user with the ones in this payload
      requestBody:
        content:
          "application/json":
            schema:
              type: array
              items:
                $ref: "#/components/schemas/JournalGroup"
            example:
              - order_number: 1
                name: breakfast
                user_id: 1
              - order_number: 2
                name: lunch
                user_id: 1
      responses:
        "201":
          description: Created
        "404":
          description: Not Found

  /journal/entry:
    get:
      tags:
        - journal
      summary: Get all journal entries
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: entry_date
          in: query
          required: true
          schema:
            type: string
            example: "2022-11-04"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/JournalEntryDetailed"
        "404":
          description: Not Found

  /journal/entry/create:
    post:
      tags:
        - journal
      summary: Create a journal entry
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/CreateJournalEntryPayload"
      responses:
        "201":
          description: Created
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/JournalEntryDetailed"
        "404":
          description: Not Found

  /journal/entry/update:
    post:
      tags:
        - journal
      summary: Update a journal entry
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/JournalEntry"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/JournalEntry"
        "404":
          description: Not Found

  /journal/entry/delete:
    post:
      tags:
        - journal
      summary: Delete a journal entry
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/DeleteJournalEntryPayload"
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
